blog/urls.py
from django.urls import path
from blog.views import *
from webapp.views import NewsListView


app_name = 'blog'


urlpatterns = [
    path('blog/', NewsListView.as_view(), name='blog'),
    path('single/<int:pk>/', NewsListView.as_view(), name='single'),
]

my_music/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('', include('blog.urls')),
]

webapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


from my_music import settings
from webapp import views
from webapp.views import *

app_name = 'webapp'

urlpatterns = [
    path('', index, name='home'),
    path('music/', music_about, name='music'),
    path('events/', events, name='events'),
    path('eventsdat/', eventsdat, name='eventsdat'),
    path('concert/', concert, name='concert'),
    path('tests_one/', tests_one, name='tests_one'),

    path('login/', CRLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='webapp/logout.html'), name='logout'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('accounts/regitster/done/', RegisterDoneView.as_view(), name='register_done'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('merch/<int:merch_id>/like/', like_merch, name='like_merch'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/main/base.html
{% load static %}

<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">

{% block head %}
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>PaRAnoia | DOlls</title>
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'webapp/images/pdnof.png' %}">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'webapp/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <!--Default CSS-->
    <link href="{% static 'webapp/css/default.css' %}" rel="stylesheet" type="text/css">
    <!--Custom CSS-->
    <link href="{% static 'webapp/css/style.css' %}" rel="stylesheet" type="text/css">
    <!--Plugin CSS-->
    <link href="{% static 'webapp/css/plugin.css' %}" rel="stylesheet" type="text/css">
    <!--Font Awesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">

</head>
{% endblock %}

<body>

    <!-- Preloader -->
    <div id="preloader">
        <div id="status"></div>
    </div>
    <!-- Preloader Ends -->

    <!-- header start -->
    <header class="main_header_area">
        <div class="header-content">
            <div class="container">
                <div class="links links-left">
                    <ul>
                        <li><a href="mailto:paranoiadolls@gmail.com"><i class="fa fa-envelope" aria-hidden="true"></i> paranoiadolls@gmail.com</a></li>
                        <li><a href="tel:+375336111777"><i class="fa fa-phone" aria-hidden="true"></i> +375336111777</a></li>
                    </ul>
                </div>
                <div class="links links-right pull-right">
                    <ul>
                        {% if user.is_authenticated %}
                            <li style="color: gold">{{ user.username }}</li>
                            <li {% if request.resolver_match.url_name == 'logout' %}class="active"{% endif %}><a
                                    href="{% url 'webapp:logout' %}" class="nav-link">Logout</a></li>
                        {% else %}
                            <li {% if request.resolver_match.url_name == 'login' %}class="active"{% endif %}><a
                                    href="{% url 'webapp:login' %}" data-toggle="modal"><i
                                    class="fa fa-user" aria-hidden="true"></i> Login</a></li>
                            <li {% if request.resolver_match.url_name == 'register' or request.resolver_match.url_name == 'register_done' %}class="active"{% endif %}>
                                <a href="{% url 'webapp:register' %}"><i class="fa fa-pen"
                                                                         aria-hidden="true"></i>
                                    Register</a></li>
                        {% endif %}

                        <li>
                            <ul class="social-links">
                                <li><a href="#"><i class="fab fa-facebook" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fab fa-youtube" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fab fa-google-plus" aria-hidden="true"></i></a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- Navigation Bar -->
        <div class="header_menu affix-top">
            <nav class="navbar navbar-default">
                <div class="container">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <a class="navbar-brand" href="{% url 'webapp:home' %}">
                            <img alt="logo1" src="{% static 'webapp/images/pd_logo2.png' %}" class="logo-black">
                        </a>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav" id="responsive-menu">
                            <li {% if request.resolver_match.url_name == 'home' %}class="active"{% endif %}><a href="{% url 'webapp:home' %}" class="nav-link">О группе</a></li>
                            <li {% if request.resolver_match.url_name == 'eventsdat' %}class="active"{% endif %}><a href="{% url 'webapp:eventsdat' %}" class="nav-link">Афиша</a></li>
                            <li {% if request.resolver_match.url_name == 'concert' %}class="active"{% endif %}><a href="{% url 'webapp:concert' %}" class="nav-link">Концерты</a></li>
                            <li {% if request.resolver_match.url_name == 'music' %}class="active"{% endif %}><a href="{% url 'webapp:music' %}" class="nav-link">Дискография</a></li>
                            <li {% if request.resolver_match.url_name == 'events' %}class="active"{% endif %}><a href="{% url 'webapp:events' %}" class="nav-link">Мерч</a></li>
                            <li {% if request.resolver_match.url_name == 'blog' or request.resolver_match.url_name == 'single' %}class="active"{% endif %}><a href="{% url 'blog:blog' %}" class="nav-link">Блог</a></li>
                        </ul>
                        <div class="nav-btn">
                            <a href="{% url 'webapp:eventsdat' %}" class="btn btn-orange">Купить Билет</a>
                        </div>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
                <div id="slicknav-mobile"></div>
            </nav>
        </div>
        <!-- Navigation Bar Ends -->
    </header>
    <!-- header Ends -->


    <!-- script js for music -->

    <script>
    function playAudio() {
      var audio = document.getElementById("myAudio");
      audio.play();
    }
    </script>

    <!-- end script js for music -->

    {% block content %}{% endblock %}


    <!-- Footer Starts -->
    <footer class="footer-style-1">
        <div class="newsletter">
            <div class="container">
                <div class="section-title title-white">
                    <h2>Подпишись на музыку <span>PaRAnoiaDOlls</span></h2>
                    <p>Подпишитесь на нашу рассылку и будьте в курсе всех новостей и концертов нашей рок-группы!
                        Получайте первыми информацию о новых релизах, будьте в курсе грядущих выступлений и получайте
                        эксклюзивные материалы о жизни группы.
                        Никакого спама, только рок-н-ролл!</p>
                </div>
                <div class="newsletter-form">
                    <form method="post" action="{% url 'webapp:subscribe' %}">
                        {% csrf_token %}
                        <input type="email" name="email" placeholder="Введите ваш email" required>
                        <a href="{% url 'webapp:subscribe' %}" class="btn btn-orange">Подписаться</a>
                    </form>
                </div>
            </div>
        </div>
        <div class="footer-top">
            <div class="container">
                <div class="footer-content">
                    <div class="row">
                        <div class="col-md-3 col-sm-6 col-xs-12">
                            <div class="footer-about">
                                <h4>О группе</h4>
                                <p>PaRAnoiaDOlls - рок-группа, основана в Беларуси в 2010 году.</p>
                                <p>Группа исполняет альтернативный рок и считается одной из самых оригинальных и эксцентричных групп на Беларуской рок-сцене.</p>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6 col-xs-12">
                            <div class="quick-links">
                                <h4>Краткая Информация</h4>
                                <ul>
                                    <li><a href="{% url 'webapp:home' %}">Главная</a></li>
                                    <li><a href="{% url 'webapp:eventsdat' %}">Афиша</a></li>
                                    <li><a href="{% url 'webapp:concert' %}">Концерты</a></li>
                                    <li><a href="{% url 'webapp:music' %}">Дискография</a></li>
                                    <li><a href="{% url 'webapp:events' %}">Мерч</a></li>
                                    <li><a href="{% url 'blog:blog' %}">Блог</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6 col-xs-12">
                            <div class="footer-payment">
                                <h4>Мы принимаем</h4>
                                <ul>
                                    <li><img src="{% static 'webapp/images/icons/visa.png' %}" alt="image"></li>
                                    <li><img src="{% static 'webapp/images/icons/mastercard.png' %}" alt="image"></li>
                                    <li><img src="{% static 'webapp/images/icons/americanexpress.png' %}" alt="image"></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6 col-xs-12">
                            <div class="footer-contact">
                                <h4>Контакты</h4>
                                <ul>
                                    <li><a href="mailto:paranoiadolls@gmail.com"><i class="fa fa-envelope" aria-hidden="true"></i>paranoiadolls@gmail.com</a></li>
                                    <li><a href="tel:+375336111777"><i class="fa fa-phone" aria-hidden="true"></i>+375336111777</a></li>
                                    <li><i class="fa fa-map-marker" aria-hidden="true"></i> Адрес: 1-ый переулок Космонавтов</li>
                                    <li>Ракета: N13</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                <div class="copyright-content text-center">
                    <p class="white">Copyright 2023. Made with <span><a href="https://t.me/ultravioletpartyeyes">Phoenix Pegasus</a></span>.
                        All Rights Reserved. <a href="#">PaRAnoiaDOlls</a></p>
                    <ul>
                        <li><a href="#" class="white"><i class="fab fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fab fa-youtube" aria-hidden="true"></i></a></li>
                        <li><a href="#" class="white"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>
                        <li><a href="#" class="white"><i class="fab fa-google-plus" aria-hidden="true"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Ends -->

    <!-- Back to top start -->
    <div id="back-to-top">
        <a href="#"></a>
    </div>
    <!-- Back to top ends -->

{#    <div class="modal fade" id="login" role="dialog">#}
{#        <div class="modal-dialog">#}
{#            <div class="login-content">#}
{#                <div class="login-image">#}
{#                    <img src="{% static 'webapp/images/pdlogo1.png' %}" alt="image">#}
{#                </div>#}
{#                <h3>Войти в аккаунт</h3>#}
{#                <form>#}
{#                    <div class="form-group">#}
{#                        <input type="email" placeholder="Введите почту">#}
{#                    </div>#}
{#                    <div class="form-group">#}
{#                        <input type="password" placeholder="Введите пароль">#}
{#                    </div>#}
{#                    <div class="form-group form-checkbox">#}
{#                        <input type="checkbox"> Запомнить меня#}
{#                        <a href="#">Забыли пароль?</a>#}
{#                    </div>#}
{#                </form>#}
{#                <div class="form-btn">#}
{#                    <a href="{% url 'login' %}" class="btn btn-orange">Войти</a>#}
{#                    <p>Нужен аккаунт?<a href="#"> Создайте свой аккаунт PaRAnoiaDOlls</a></p>#}
{#                </div>#}
{#                <ul class="social-links">#}
{#                    <li><a href="#"><i class="fab fa-facebook" aria-hidden="true"></i></a></li>#}
{#                    <li><a href="#"><i class="fab fa-youtube" aria-hidden="true"></i></a></li>#}
{#                    <li><a href="#"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>#}
{#                    <li><a href="#"><i class="fab fa-linkedin" aria-hidden="true"></i></a></li>#}
{#                </ul>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}



    <!-- *Scripts* -->
    <script src="{% static 'webapp/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'webapp/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'webapp/js/plugin.js' %}"></script>
    <script src="{% static 'webapp/js/main.js' %}"></script>
    <script src="{% static 'webapp/js/custom-nav.js' %}"></script>
    <script src="{% static 'webapp/js/custom-swiper2.js' %}"></script>
    <script src="{% static 'webapp/js/custom-singledate.js' %}"></script>


</body>
</html>