blog/urls.py
from django.urls import path
from blog.views import *
from webapp.views import NewsListView


app_name = 'blog'


urlpatterns = [
    path('blog/', NewsListView.as_view(), name='blog'),
    path('single/<int:pk>/', NewsListView.as_view(), name='single'),
]

my_music/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('', include('blog.urls')),
]

webapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


from my_music import settings
from webapp import views
from webapp.views import *

app_name = 'webapp'

urlpatterns = [
    path('', index, name='home'),
    path('music/', music_about, name='music'),
    path('events/', events, name='events'),
    path('eventsdat/', eventsdat, name='eventsdat'),
    path('concert/', concert, name='concert'),
    path('tests_one/', tests_one, name='tests_one'),

    path('login/', CRLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='webapp/logout.html'), name='logout'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('accounts/regitster/done/', RegisterDoneView.as_view(), name='register_done'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('merch/<int:merch_id>/like/', like_merch, name='like_merch'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render

def blog(request):
    return render(request, 'blog/news_list.html')



# def post(request, pk):
#     post = Post.objects.get(pk=pk)
#     comments = Comment.objects.filter(post_id=pk)
#     categories = Category.objects.annotate(num_posts=Count('post'))
#     context = {
#         'post': post,
#         'comments': comments,
#         'categories': categories
#     }
#     return render(request, 'blog/post.html', context)

blog/templates/blog/news_list.html
{% extends 'main/base.html' %}
{% load static %}


    {% block content %}

    <!-- breadcrumb Starts -->
    <section class="breadcrumb-outer">
        <div class="container">
            <div class="breadcrumb-content">
                <h2>Новости</h2>
                <nav aria-label="breadcrumb">
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'webapp:home' %}">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">На главную</li>
                    </ul>
                </nav>
            </div>
        </div>
    </section>
    <!-- breadcrumb Endss -->

    <!-- detail starts -->
        <section class="details">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="list-content">
                            <div class="row">
                                {% for news in news_list %}
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        <div class="news-item">
                                            <div class="news-image">
                                                <img src="{{ news.photo.url }}" alt="{{ news.title }}">
                                            </div>
                                            <div class="news-content">
                                                <p class="date">{{ news.pub_date }}</p>
                                                <h4>{{ news.title }}</h4>
                                                <div class="room-services">
                                                    <ul>
                                                        <li><i class="fa fa-user" aria-hidden="true"></i> By Jack
                                                            Daniels
                                                        </li>
                                                        <li><i class="fa fa-comment" aria-hidden="true"></i> 3 comments
                                                        </li>
                                                    </ul>
                                                </div>
                                                <p>{{ news.description }}</p>
                                                <a href="{% url 'blog:single' news.pk %}">READ MORE <i
                                                        class="fas fa-angle-double-right"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="pagination-content text-center">
                            <ul class="pagination">
                                {% if is_paginated %}
                                    <li class="page-item{% if not page_obj.has_previous %} disabled{% endif %}">
                                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                                                {% if not page_obj.has_previous %} tabindex="-1"{% endif %}>Previous</a>
                                    </li>
                                    {% for page in paginator.page_range %}
                                        {% if page_obj.number == page %}
                                            <li class="page-item active">
                                                <a class="page-link" href="#">{{ page }}<span
                                                        class="sr-only">(current)</span></a>
                                            </li>
                                        {% else %}
                                            <li class="page-item"><a class="page-link"
                                                                     href="?page={{ page }}">{{ page }}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                    <li class="page-item{% if not page_obj.has_next %} disabled{% endif %}">
                                        <a class="page-link" href="?page={{ page_obj.next_page_number }}"
                                                {% if not page_obj.has_next %} tabindex="-1"{% endif %}>Next</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    <!-- detail Ends -->

    <!-- Back to top start -->
    <div id="back-to-top">
        <a href="#"></a>
    </div>
    <!-- Back to top ends -->

    <div class="modal fade" id="login" role="dialog">
        <div class="modal-dialog">
            <div class="login-content">
                <div class="login-image">
                    <img src="{% static 'blog/images/logo-black.png' %}" alt="image">
                </div>
                <h3>Hello!Sign into your account</h3>
                <form>
                    <div class="form-group">
                        <input type="email" placeholder="Enter email address">
                    </div>
                    <div class="form-group">
                        <input type="password" placeholder="Enter password">
                    </div>
                    <div class="form-group form-checkbox">
                        <input type="checkbox"> Remember Me
                        <a href="#">Forgot password?</a>
                    </div>
                </form>
                <div class="form-btn">
                    <a href="#" class="btn btn-orange">LOGIN</a>
                    <p>Need an Account?<a href="#"> Create your Gautama account</a></p>
                </div>
                <ul class="social-links">
                    <li><a href="#"><i class="fab fa-facebook" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fab fa-twitter" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fab fa-linkedin" aria-hidden="true"></i></a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="modal fade" id="register" role="dialog">
        <div class="modal-dialog">
            <div class="login-content">
                <div class="login-image">
                    <img src="{% static 'blog/images/logo-black.png' %}" alt="image">
                </div>
                <h3>Awesome! Create a Gautama Account</h3>
                <form>
                    <div class="form-group">
                        <input type="text" placeholder="Enter username">
                    </div>
                    <div class="form-group">
                        <input type="email" placeholder="Enter email address">
                    </div>
                    <div class="form-group">
                        <input type="password" placeholder="Enter password">
                    </div>
                    <div class="form-group">
                        <input type="password" placeholder="Confirm password">
                    </div>
                </form>
                <div class="form-btn">
                    <a href="#" class="btn btn-orange">SIGN UP</a>
                </div>
                <ul class="social-links">
                    <li><a href="#"><i class="fab fa-facebook" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fab fa-twitter" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fab fa-linkedin" aria-hidden="true"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
    {% endblock %}

blog/templates/blog/single-full.html
{% extends 'main/base.html' %}
{% load static %}


    {% block content %}
    <!-- breadcrumb Starts -->
    <section class="breadcrumb-outer">
        <div class="container">
            <div class="breadcrumb-content">
                <h2>Single Full Width</h2>
                <nav aria-label="breadcrumb">
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Single Full Width</li>
                    </ul>
                </nav>
            </div>
        </div>
    </section>
    <!-- breadcrumb Ends -->

    <!-- Single Starts -->
    <section class="single bg-white">
        <div class="container">
            <div class="single-image">
                <img src="{% static 'blog/images/single1.jpg' %}" alt="image">
            </div>
            <div class="single-detail mar-top-30">
                <div class="row">
                    <div class="col-md-1 col-md-offset-1 col-sm-12 col-xs-12">
                        <div class="single-date">
                            <p><span>15</span>August,2019</p>
                        </div>
                    </div>
                    <div class="col-md-9 col-sm-12 col-xs-12">
                        <div class="single-content">
                            <h4>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis varius ligula non tellus euismod fermentum. </h4>
                            <ul class="author">
                                <li><i class="fa fa-user" aria-hidden="true"></i> By Jack Daniels</li>
                                <li><i class="fa fa-comment" aria-hidden="true"></i> 3 comments</li>
                            </ul>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis varius ligula non tellus euismod fermentum. Nulla quis enim ut est dapibus luctus quis quis enim. Ut bibendum ultricies nisl ut aliquam. Ut in arcu id nunc elementum ultricies eu eget lacus nam at neque lorem.</p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis varius ligula non tellus euismod fermentum. Nulla quis enim ut est dapibus luctus quis quis enim. Ut bibendum ultricies nisl ut aliquam. Ut in arcu id nunc elementum ultricies eu eget lacus. Nam at neque lorem. Vivamus faucibus ex et hendrerit venenatis. Donec quis dignissim purus nullam semper ullamcorper odio vitae dictum.</p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis varius ligula non tellus euismod fermentum. Nulla quis enim ut est dapibus luctus quis quis enim. Ut bibendum ultricies nisl ut aliquam. Ut in arcu id nunc elementum ultricies eu eget lacus nam at neque lorem.</p>
                            <blockquote>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis varius ligula non tellus euismod fermentum. Nulla quis enim ut est dapibus luctus quis quis enim.Proin elit odio, maximus in mollis nec, vestibulum quis nisl.</p>
                            </blockquote>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis varius ligula non tellus euismod fermentum. Nulla quis enim ut est dapibus luctus quis quis enim. Ut bibendum ultricies nisl ut aliquam. Ut in arcu id nunc elementum ultricies eu eget lacus nam at neque lorem.</p>
                        </div>
                        <div class="single-tags clearfix">
                            <div class="tags pull-left">
                                <i class="fa fa-tags" aria-hidden="true"></i>
                                <ul>
                                    <li>#hotel</li>
                                    <li>#luxurious</li>                                    
                                    <li>#comfort</li>
                                    <li>#5 star</li>
                                    <li>#Air condition</li>
                                </ul>
                            </div>
                            <div class="title-right pull-right">
                                <ul>
                                    <li class="facebook"><i class="fab fa-facebook"></i></li>
                                    <li class="twitter"><i class="fab fa-twitter"></i></li>
                                    <li class="linkedin"><i class="fab fa-linkedin"></i></li>
                                    <li class="pinterest"><i class="fab fa-pinterest"></i></li>
                                </ul>
                            </div>
                        </div>
                        <div class="next-posts clearfix">
                            <a href="#">
                                <div class="prev next-item pull-left">
                                    <i class="fa fa-angle-left" aria-hidden="true"></i>
                                    <span>Previous Post</span>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                                </div>
                            </a>
                            <a href="#">
                                <div class="next next-item pull-right">
                                    <i class="fa fa-angle-right" aria-hidden="true"></i>
                                    <span>Next Post</span>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                                </div>
                            </a>
                        </div>
                        <div class="detail-review">
                            <h4>3 Comments</h4>
                            <div class="review-outer">
                                <ul>
                                    <li>
                                        <div class="review-item">
                                            <div class="review-image">
                                                <img src="{% static 'blog/images/review1.jpg' %}" alt="image">
                                            </div>
                                            <div class="review-content">
                                                <h5>Micheal Clordy</h5>
                                                <a href="#"><i class="fa fa-reply" aria-hidden="true"></i> Reply</a>
                                                <p class="date">November 10,2018 at 3:10 pm</p>
                                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id iaculis arcu. Aenean non dolor magna. In sed consectetur nisi. Sed venenatis, nibh sit amet sodales ullamcorper, ipsum orci condimentum tortor, et cursus veli.tturpis at justo. Vivamus pellentesque volutpat urna vel eleifend. </p>
                                            </div>
                                        </div>
                                         <ul>
                                            <li>
                                                <div class="review-item">
                                                    <div class="review-image">
                                                        <img src="{% static 'blog/images/review2.jpg' %}" alt="image">
                                                    </div>
                                                    <div class="review-content">
                                                        <h5>Micheal Clordy</h5>
                                                        <a href="#"><i class="fa fa-reply" aria-hidden="true"></i> Reply</a>
                                                        <p class="date">November 10,2018 at 3:10 pm</p>
                                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id iaculis arcu. Aenean non dolor magna. In sed consectetur nisi. Sed venenatis, nibh sit amet sodales ullamcorper, ipsum orci condimentum tortor, et cursus veli.tturpis at justo. Vivamus pellentesque volutpat urna vel eleifend. </p>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </li>
                                    <li>
                                        <div class="review-item">
                                            <div class="review-image">
                                                <img src="{% static 'blog/images/review3.jpg' %}" alt="image">
                                            </div>
                                            <div class="review-content">
                                                <h5>Micheal Clordy</h5>
                                                <a href="#"><i class="fa fa-reply" aria-hidden="true"></i> Reply</a>
                                                <p class="date">November 10,2018 at 3:10 pm</p>
                                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id iaculis arcu. Aenean non dolor magna. In sed consectetur nisi. Sed venenatis, nibh sit amet sodales ullamcorper, ipsum orci condimentum tortor, et cursus veli.tturpis at justo. Vivamus pellentesque volutpat urna vel eleifend. </p>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="comment-box mar-top-20">
                                <h4>Leave a message</h4>
                                <form>
                                    <div class="row">
                                        <div class="form-group col-xs-6">
                                            <input type="text" class="form-control" id="fname" placeholder="First Name">
                                        </div>
                                        <div class="form-group col-xs-6">
                                            <input type="text" class="form-control" id="lname" placeholder="Last Name">
                                        </div>
                                        <div class="form-group col-xs-6">
                                            <input type="email" class="form-control" id="email" placeholder="Email">
                                        </div>
                                        <div class="form-group col-xs-6">
                                            <input type="text" class="form-control" id="phnumber" placeholder="Phone">
                                        </div>
                                        <div class="textarea col-xs-12">
                                            <textarea placeholder="Enter a message"></textarea>
                                        </div>
                                        <div class="col-xs-12">
                                            <div class="comment-btn">
                                                <a href="#" class="btn btn-orange">Submit</a>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Single Ends -->
    {% endblock %}